### ISSUE TITLE
Terminology bikeshed: what to call vats-as-far-as-the-protocol-can-tell?

### ISSUE THREAD

**Issue by zenhack** [ocapn/ocapn#18]
I put this to the IRC channel a while back, but nobody weighed in. It is a minor terminology bikeshed, but:

The term "vat" implies an event loop, but I want a word for something that is a vat as far as protocol issues are concerned, but without specifying its internal notion of concurrency. E.g. it could be an E-style event loop, but it could also be a multithreaded process, as is the case with the Go & Haskell implementations of Cap'n Proto. IIRC @erights objected to calling this a vat on the cap-talk mailing list at some point, but agreed that the event-loop notion of a vat was "mostly orthogonal" to CapTP.

So what do we call a CapTP not-exactly-a-vat in the general case?

(I'm half tempted to start coming up with weird puns about things that contain actors: stage, troupe... but it might be worth trying to come up with something that is actually not confusing, which "vat" kindof is anyway...)

**Comment by gobengo** [comment]
What would this designate beyond the word "actor"? "Stage" (public view of actors)?

**Comment by aschrijver** [comment]
In Akka they call this an `ActorSystem`, and if that is covering the load, is a less abstract more familiar term. [Proto.Actor](https://proto.actor/docs/) (started by one of former Akka devs) for .NET, Kotlin and Golang also uses this term.

Microsoft Orleans uses the term [Silo's](https://learn.microsoft.com/en-us/dotnet/orleans/overview#what-are-silos).

Vert.x uses the term [Verticles](https://vertx.io/docs/vertx-core/java/#_verticles), where based on an `AbstractVerticle` you have sub-classes either be regular `Verticle` (has its own event loop) or `WorkerVerticle` (has its own thread pool).

**Comment by zenhack** [comment]
Some of these are different than the distinction I'm making.

TBH I wonder if we should just use Vat to mean the protocol concept, and
if we mean event loop just say event loop.

Quoting Arnold Schrijver (2022-12-09 04:01:02)

**Comment by erights** [comment]
No sorry, I've very clearly defined "vat" as the computational unit. It is more than just an event-loop. The other main defining properties is that a vat is a single thread of control, and that a vat is only ever asynchronously coupled to other vats. JavaScript event-loops (aka "agents") were vats before the introduction of SharedArrayBuffer, enabling them to interact synchronously. Hardened JavaScript (aka "SES") event loops are vats because of the required absence of SharedArrayBuffer or any other synchronizing mechanism.

Agoric has the same dichotomy you're wrestling with. See https://www.youtube.com/watch?v=sfIMOu2Gktg&list=PLzDw4TTug5O1oHRbp2HkcvKABAY9FKsmG , whose relevant graphic is

<img width="1809" alt="image" src="https://user-images.githubusercontent.com/273868/206885250-f855b845-92da-462e-8267-0363f1f7fec4.png">

Each pink square is a physical machine. Each stack of pink squares is a logical machine form by replication and consensus among the physical machines in that stack. For us, typically a blockchain. This replication is not relevant to our problem here but I mention it so the whole diagram can be understood.

The red pipes between physical machines are the protocol which connects them. Each red pipe itself is one IBC (Inter BlockChain) connection, on which we run a vattp (aka "netlayer") connection. The blue lines are the remote ocaps being multiplexed by CapTP over that netlayer connection. The pink rightward pointing pentagon is an message sent over captp.

The endpoints of this captp network protocol are the logical machines, on which we run a swingset, consisting of the SwingSet kernel, the tilted grey square in the middle of each logical machine, and a set of vats, which are the green pentagons (squares with a cutoff corner) surrounding it. Each of the blue trapezoids is a CapTP connection. The vats connecting directly to the network --- an example in the upper left machine is the lower right vat --- are the "comms vats".

The blue circles are the objects. As will surprise no one, the circle in the upper left is Alice and the circle in the upper right is Bob. Alice's vat is VatA and Bob's vat is VatB. Alice has sent a message to Bob represented by the pentagon message arrow. The current placement of that arrow is just a snapshot of its journey. Watch the talk to see more of that journey.

Remember that this diagram is our external objective god's eye view that sees more than the entities within the system sees. When Alice sends a message through VatA's CapTP connection to Bob, she doesn't know anything about VatB. It could be on the same machine or across the network. Even if on the same machine, all the vats on the same machine are aggregated to the SwingSet kernel so, to Alice, for most (not all) purposes, it is as if all objects not in VatA might as well be in one vat representing "all the objects in the rest of the world". The comms vat has one CapTP connection for each remote machine, and one for talking to the SwingSet kernel, which collectively represents all the objects on that machine not on the comms vat. The comms vat truly doesn't care which vat on the local machine an object is in.

As the left comms vat speaks over the CapTP protocol to the comms vat on the right, the left comms vat doesn't know that the right machine even is a swingset with a comms vat. As far as it knows, it is speaking to a unitary vat on the right housing all of the objects it reaches through that connection.

Each CapTP has a connection trapezoid on each side, housing the c-list tables enabling each side to name (number) the capabilities that the other side permits it to access. What is behind that trapezoid is mysterious and can vary greatly. So I agree that these should not be called "vats". In our god's eye view of the Agoric systems, these are not even the vats of interest. Unless someone has a better suggestion, I suggest "endpoints". For each endpoint of a captp connection, the other endpoint is the "counter-party".

**Comment by erights** [comment]
I doubt it should effect our terminology much, but there is an important wrinkle in our future plans that will pierce some of the opacity of the above picture. We intend vats to be units of transparent migration. During operation, we intend to support moving VatB, for example, from the right machine to the left, becoming another vat on the same machine as VatA, without either noticing that anything has changed. Every message that would have been delivered must still be delivered, obeying all the ordering constraints. On the one hand, that's why it is important that VatA not know or care where VatB is. OTOH, to bring about this migration will take much coordination with the comms vats, revealing vat separateness as a consequence.

**Comment by zenhack** [comment]
I don't love endpoint, in that it evokes an address of some type, giving it a very "outside view" bias. Maybe "[captp/opcan] participant?"

**Comment by erights** [comment]
I like "participant"

**Comment by zenhack** [comment]
Alternatives:

- Machine. Advantage: I think this is consistent with what Goblins already uses. Disadvantage, I worry people will confuse it with an actual, physical machine. And iirc Agoric might use this term to mean something slightly different?
- Peer. A lot of the same advantages of participant, but rolls off the tounge a bit easier.

**Comment by erights** [comment]
"Machine" is compatible enough with how Agoric uses the term. In explaining diagrams like the one above, we say that pink rectangle is a physical machine, but each stack of pink rectangles is a logical machine, such as a blockchain, that is built by agreement among the physical machines in that stack.

But "Peer" is great! Definitely my favorite so far. What are the endpoints of a peer-to-peer protocol? Peers, of course!

**Comment by jar398** [comment]
Decided on 'peer' at the 10 Sept 2024 meeting.
