### ISSUE TITLE
core data types: string details, e.g. lone surrogate

### ISSUE THREAD

**Issue by dckc** [ocapn/ocapn#47]
In https://github.com/ocapn/ocapn/issues/5#issuecomment-1550481111 @erights writes:
> What does capnp do when an incoming string allegedly in UTF-8 encodes a lone surrogate?

Let's please have a test case for that.

In https://github.com/ocapn/ocapn/issues/5#issuecomment-1550546951 @zenhack writes:
> I'll make a proposal: ocapn strings are isomorphic to lists of integers in the range [0, 2^21).

**Comment by erights** [comment]
It is up to each endpoint definition to define the binding of the protocol data model to their internal language model, as long as they preserve round-tripping, i.e., the distinction between the equivalence classes. There should be nothing in the protocol definition, indeed cannot be, that prohibits a conforming endpoint from defining a language binding that transforms through ROT13, since it still round trips.

That said, this does create a separate obligation on those endpoint definitions to define that language binding. A language binding that specifies translation though ROT13 is, hopefully, a language binding no one uses.

**Comment by dckc** [comment]
ok, so a test for "ABC" in, "ABC" out is out of scope for the data model alone, but the test framework might include bindings on each end.

**Comment by erights** [comment]
Yes. Taking the language binding into account, in bounds is testing that "Something that maps to the protocol 'ABC' round trips to something that maps to the protocol 'ABC'" where "maps to" means "according to the language binding".

**Comment by erights** [comment]
My text is likely not great standards language. I'm happy with any rephrasing that means the same thing. (meta analogy intended ;) )

**Comment by erights** [comment]
@zenhack 
> I'll make a proposal: ocapn strings are isomorphic to lists of integers in the range [0, 2^21).

I really love @zenhack's proposal and hope we can keep it. But I found a problem with it we need to discuss. The proposal above would require that the distinction between a proper surrogate pair vs the unicode char it encodes be preserved. That this distinction round trip. Put another way, that the data model holds them to be in distinct equivalence classes.

For languages that rely on the UTF-8-like representation and encode/decode algorithm, that might be the least effort outcome. But for languages like Java and standard (non-XS) JS, their native string encoding is UTF-16. Their OCapN language binding can only map a proper surrogate pair to an OCapN encoding of those two 16 bit values, or it can map it to the one 21 bit value. It cannot do both. Whichever it does, the other kind of OCapN string does not round trip through any language string natural to that language.

We could loosen the round trip criteria consider the two 16 values that happens to be a proper surrogate pair to be in the same equivalence class as the 21-bit value it UTF-16 encodes. IOW, if one of these representations round trips back as the other, that OCapN consider that a valid round trip.

One terribly unpleasant thing about this answer: it would make it terribly painful to define a lexicographic order among such strings. The natural lexicographic order according to one representation would be different that the order according to another, allegedly equivalent, representation. IOW, the natural sort order would not be pass-invariant. (Note that comparison/sort order are not part of the code data model we're trying to agree on. It would just create pain for optional higher layers.)

Hopefully, someone in the room is more acquainted with Unicode than I, and can point out something I'm missing.

**Comment by dckc** [comment]
For reference, Agoric uses [CESU-8](https://en.wikipedia.org/wiki/CESU-8). We have a test case resulting from a long discussion in an issue:

 - https://github.com/Agoric/agoric-sdk/pull/4920
 - https://github.com/Agoric/agoric-sdk/issues/2118

> Their OCapN language binding can only map a proper surrogate pair to an OCapN encoding of those two 16 bit values, or it can map it to the one 21 bit value. It cannot do both. Whichever it does, the other kind of OCapN string does not round trip through any language string natural to that language.

CESU-8 maps it to two 16 bit values "and then each surrogate code point is encoded in UTF-8."

It's somewhat like utf-8, but sufficiently different that you can't just wave your hands at the difference. guile scheme most likely has utf-8 support out of the box but not CESU-8. The HTML spec goes so far has to prohibit support for CESU-8 in [13.2.3.3 Character encodings](https://html.spec.whatwg.org/multipage/parsing.html#character-encodings)

I wondered what rust folks do... there's a crate for that: [cesu8 \- Rust](https://docs.rs/cesu8/latest/cesu8/). But it says stuff like "Yes, this is ugly. Use of this encoding is discouraged by the Unicode Consortium. It's OK for working with existing internal APIs, but it should not be used for transmitting or storing data."

**Comment by dckc** [comment]
Idea: 2^21 is 0x200_000; the highest unicode code point is 0x10F_FFF. There are 0x800 surrogates. So a JS language binding could reserve, say, 0x180_000 to 0x180_7FF for surrogates.

How we encode them for transfer is a bit of a puzzle, but CESU-8 is one solution, as well as the more compatible [WTF-8](https://simonsapin.github.io/wtf-8/). Wikipedia notes [PEP 383](https://peps.python.org/pep-0383/) as another solution.

I wonder how much utility we'll get out of this "abstract sequence over [0, 2^21)" notion, though. In tests, writing [65, 66, 67] instead of "ABC" will get old real quick. The test framework will most likely include a text encoding, and it'll be pretty hard to see that the encoding isn't quite part of the OCapN spec. To resolve this issue to my satisfaction, we ought to have a test that shows how we handle lone surrogates between Agoric, Spritely, and capn-proto (even if the answer is: "we don't").

**Comment by gibson042** [comment]
> One unpleasant thing about this answer: it would make it terribly painful to define a lexicographic order among such strings. The natural lexicographic order according to one representation would be different that the order according to another, allegedly equivalent, representation. IOW, the natural sort order would not be pass-invariant. (Note that comparison/sort order are not part of the core data model we're trying to agree on. It would just create pain for optional higher layers.)

I am also concerned about this, and believe the correct ordering to be by Unicode code point rather than by UTF-16 code unit (IOW, native JavaScript string comparison gets it wrong; `"\u{0FF41}" < "\u{1D306}"` unfortunately evaluates to **false** because the U+1D306 TETRAGRAM FOR CENTRE code point is represented as the surrogate pair `"\uD834\uDF06"`). AFAICT, this is a family of latent bugs in Endo.

As for transmitting lone surrogates, both [CESU-8](https://www.unicode.org/reports/tr26/) and [WTF-8](https://simonsapin.github.io/wtf-8/#the-wtf-8-encoding) declare theirselves to be inappropriate for interchange. It would be great to restrict strings to Unicode scalar values (which do not include surrogate code points U+D800 through U+DFFF) and use UTF-8 in the wire format, which is not too difficult to validate even in JavaScript—such as by scanning for unpaired surrogates or by replacing well-formed [high surrogate, low surrogate] pairs and then scanning for any leftover surrogates, in both approaches remembering to include `\uHHHH` encoded escape sequences if the input is JSON text, e.g.
```js
const parseIJSON = jsonText => {
  const cleaned = jsonText.replace(
    /\\\\|(?:[\uD800-\uDBFF]|\\ud[89ab][0-9a-f]{2})(?:[\uDC00-\uDFFF]|\\ud[c-f][0-9a-f]{2})/gi,
    '',
  );
  !/[\uD800-\uDFFF]|\\uD[89a-f][0-9a-f]{2}/i.test(cleaned) ||
    Fail`input contains unpaired surrogates`;
  return JSON.parse(jsonText);
};
```
or a more efficient equivalent using regular expression lookaround rather than replacement.

**Comment by erights** [comment]
Some on this string discussion happened on the original thread starting at https://github.com/ocapn/ocapn/issues/5#issuecomment-1595721403 . Please consider this a virtual include of that subthread in this thread.

**Comment by dpwiz** [comment]
What is the use case for sending things that are 1) unrepresentable in UTF8 2) have "text" semantics?

**Comment by dckc** [comment]
> What is the use case for sending things that are 1) unrepresentable in UTF8 2) have "text" semantics?

JavaScript strings include unpaired surrogates...

"it should be able to encode any string representable in JSON, which therefore must cover such horrors as unpaired surrogates."

Whether these monsters round-trip thru ocapn is the subject of this issue.

**Comment by dpwiz** [comment]
> JavaScript strings include unpaired surrogates...

Okaaay.... Why would one want to send such things as text?

**Comment by zenhack** [comment]
Question for agoric folks: would it be acceptable if strings containing lone surrogates simply were not passable? What about invalid surrogate pairs?

**Comment by erights** [comment]
Cross referencing the discussion of protocol-layering / equivalence-classes / round-tripping at https://github.com/ocapn/ocapn/issues/47

> Well, of course, anyone can send whatever they want on the wire. So the recipients should (must, really) check incoming bytes and welcome only valid data. 

The whole discussion of strings, but especially this, raise further considerations on the base requirements of the protocol. A major motivation of ocapn is to enable interoperation between mutually suspicious machines on open networks. No matter what we say the protocol requires, it is undeniable that any participant in the protocol "can send whatever they want on the wire". The protocol definition must clearly bound the damage that a misbehaving participant can cause to its counter-parties.

The hypothetical case there, of a binary protocol transmitting 64 bit IEEE floating point values, would (IIUC) consider all possible 64 bit combinations to be a valid floating point value. The issue there is only equivalence classes, not rejection.

Here, we should consider both equivalence classes and rejection as possible ways to cope with these string representation weirdnesses. I am not yet prepared to advocate a particular position yet, but let's examine a possible one:
   * The abstract protocol only talks about valid (well formed?) Unicode sequences in the sense that
       * It is a sequence of 21-bit values to be interpreted as Unicode code points. 
       * This must exclude the 21-bit values that Unicode assigns to surrogates.
   * For all allowed concrete representation of those Unicode strings, they must round trip to a concrete representation of the same Unicode string.
   * Say that a concrete syntax of interest 
      * Includes all valid UTF-8 sequences.
      * This particular concrete syntax also allows the CESU-8 encoding for any particular Unicode code point, in the sense that a *proper* surrogate pair can be encoded by applying the UTF-8 algorithm to each surrogate pair.
      * It is therefore *allowed* for the CESU-8 encoding of a proper Unicode string to round trip as a UTF-8 encoding of the same string, and vice versa.
      * This concrete syntax does not admit binaries that do not follow the UTF-8 algorithm, i.e. (IIUC), that are outside WTF-8.
      * This concrete syntax does not admit encodings of lone surrogates, or of improper surrogate pairs. IOW, it does not admit anything that would not decode by the UTF-8 algorithm into a proper Unicode sequence as defined above.

Of course, any participant can send a binary that is not admitted by this concrete syntax. Does ocapn 
   * *require* a correct ocapn implementation to reject such a binary on input?
   * or, *allow* a correct ocapn implementation to "misunderstand" the invalid input by interpreting as some valid input, such that it would only round trip from that correct ocap participant as valid concrete syntax?

I favor the first, more restrictive requirement. But I must admit that the second weaker requirement does not violate any fundamental principles. If it were adopted as the base ocapn requirement, one could always separately define a stronger refinement of the ocapn spec that required the rejection. Any valid implementation of the stronger refined spec would still be a valid implementation of the weaker ocapn spec. Any participant could choose to obey the stronger spec.

Since both specs require a correct participant to only output binaries that correct implementors of either spec will accept, settling on the weaker spec still satisfies all our interoperability goals.

(If we go this way, I would still prefer to see us agree on the stronger spec)

**Comment by erights** [comment]
> Question for agoric folks: would it be acceptable if strings containing lone surrogates simply were not passable? What about invalid surrogate pairs?

Considering it!

@zenhack , would it be acceptable to you if ocapn requires validation and rejection of strings that contain lone or invalid surrogate pairs? Would the systems you're concerned about realistically to this validation and rejection?

**Comment by gibson042** [comment]
> Question for agoric folks: would it be acceptable if strings containing lone surrogates simply were not passable? What about invalid surrogate pairs?

@zenhack What is an "invalid surrogate pair", and in what context could an example of such be encountered? My understanding of "surrogate pair" comes from http://www.unicode.org/glossary/#surrogate_pair , in which any high surrogate UTF-16 code unit followed by any low surrogate UTF-16 code unit represents a Unicode scalar value that is also expressible in well-formed UTF-8.

**Comment by erights** [comment]
Note @dpwiz 's point

> UTF8 has SIMD'd validation routines than can guard against such things at negligible cost. And I expect every programming language worth their bytes to be able to do this or to have a library to deal with this. Infecting them with having to deal with some other platform sins is punishing the wrong side.

in case that's a concern on your side.

**Comment by erights** [comment]
> @zenhack What is an "invalid surrogate pair"

I interpreted this to mean
   * a pair of highs
   * a pair of lows
   * a low followed by a high

**Comment by erights** [comment]
Agoric and other JS folk:

If we do the normal WTF-8 to JS UTF-16 string decode followed by `isWellFormed` for validation, such that `!isWellFormed` causes rejection, do we as a result satisfy my hypothetical stronger spec above?

**Comment by zenhack** [comment]
> @zenhack , would it be acceptable to you if ocapn requires validation and rejection of strings that contain lone or invalid surrogate pairs? Would the systems you're concerned about realistically do this validation and rejection?

I'd be ok with this; I don't see getting all capnp implementations on the same page re: string validation, especially up-front (prior to field access) validation, but we can deal with this at the bridge so I don't think it's really a problem.

**Comment by zenhack** [comment]
> > @zenhack What is an "invalid surrogate pair"
> 
> I interpreted this to mean
> 
>     * a pair of highs
> 
>     * a pair of lows
> 
>     * a low followed by a high

Yes, exactly

**Comment by erights** [comment]
Regarding the two choices I mention above at https://github.com/ocapn/ocapn/issues/47#issuecomment-1610322725

> Does ocapn 
>    * *require* a correct ocapn implementation to reject such a binary on input?
 >   * or, *allow* a correct ocapn implementation to "misunderstand" the invalid input by interpreting as some valid input, such that it would only round trip from that correct ocap participant to be output as valid concrete syntax?

The second follows Postel's law: "Be conservative in what you send, be liberal in what you accept."

The first follows from Eich's law: "If you are liberal in what you accept, others will utterly fail to be conservative in what they send."

**Comment by gibson042** [comment]
> > @zenhack What is an "invalid surrogate pair"
> 
> I interpreted this to mean
> 
> * a pair of highs
> * a pair of lows
> * a low followed by a high

Ah, I believe those are all instances of unpaired surrogates (which I guess is therefore more general than "lone surrogates"). Regardless, I would support the strong validation that rejects any string including them as non-passable.

**Comment by cwebber** [comment]
To step back a moment, I think we're looking at trying to build a protocol that's forward-facing as much as possible and aiming for as broad of adoption across languages as possible.  In general, lone surrogate pairs are an artifact, per my understanding, of an accident of history with respect to UTF-16 and aren't considered valid Unicode.  I think the argument for lone surrogate pairs is coming from a good place of trying to make sure as much round trips as possible, but it could create real difficulties in languages that are themselves trying to be forward-facing and might not even have support for what's generally considered an accident of history.  The question is: is propagating support for that bug the right choice?  Sometimes it really can be, and we've considered considering other quirky things for "the way the world is" (we've agreed upon null and undefined both, and we've agreed upon negative zero) so I don't want to dismiss this possibility out of hand, but try to think thoughtfully about it.

The [wtf-8 document](https://simonsapin.github.io/wtf-8/) tries to encode and formalize how to represent lone surrogate pairs in utf-8, and has some text worth empathizing:

> WTF-8 is a hack intended to be used internally in self-contained systems with components that need to support potentially ill-formed UTF-16 for legacy reasons.
> 
> Any WTF-8 data must be converted to a Unicode encoding at the system’s boundary before being emitted. UTF-8 is recommended. _WTF-8 **must not** be used to represent text in a file format or for transmission over the Internet._

That's a strong statement, and it's also backed up by the following open W3C TAG issue: [Discourage depending on the WTF-16 nature of JavaScript strings](https://github.com/w3ctag/design-principles/issues/323)

One thing we all agree upon in the group is that we want to have OCapN be _the_ long-lived CapTP implementation across many languages, if we can accomplish it.  @erights has made the argument for JSON on these grounds, so looking at JSON's \[RFC 4627\](https://www.ietf.org/rfc/rfc4627.txt:

> JSON text SHALL be encoded in Unicode.  The default encoding is UTF-8.

There's only one agreement in JSON then, even if the encoding is not super specified (but UTF-8 is recommended): that JSON is unicode.  We should expect that many languages' support of JSON, or other string encoding tools in general, are likely to not have support for WTF-16 / WTF-8 semantics, and WTF-8 explicitly says, as quoted previously, to not be put on the wire or or on disk.  The open TAG issue concurs.  As a group taking the opportunity to hopefully define _the_ RPC protocol of the future, I suggest we be forward looking and say that the abstract data type for strings is proper unicode, and that unicode does not have semantics for lone surrogate pairs.

**Comment by jar398** [comment]
Here are some relevant remarks by @erights, indicating, as I read them, that we need some more information and analysis before deciding what to about lone surrogates.  I am relaying these comments here at his request.  Jonathan

---
On the lone surrogate issue, several points:

Absent other constraints, I would be happy to say "UTF-8 only" i.e., abstractly, "Unicode only". And to require conforming implementations to be validating --- to reject allegedly-string input that is not a Unicode string.

However,
   * I want to stay a superset of JSON, and I am getting contradictory signals about what JSON actually does in practice. I'd like to understand this better.
   * Ian had indicated that Cap'n Proto, and specifically Kenton, would be unwilling to validate on input. But we have not heard from Kenton on this.

If we define non-unicode strings to be invalid input, but we don't require validation on input, then we need to carefully state what we require an implementation to do when receiving invalid string input. For example, we could define there to be one equivalence class for round tripping per valid string only, and then try to say something about what happens when round tripping starting from an invalid string, such as: it could either error, come back as "nearby" valid strings, or come back as itself. This would allow validating implementations, some kind of normalizing implementations, and blindly non-validating implementations.

**Comment by gibson042** [comment]
> I want to stay a superset of JSON, and I am getting contradictory signals about what JSON actually does in practice. I'd like to understand this better.

JSON the text-based interchange format unequivocally supports representing strings containing unpaired surrogates that cannot themselves be expressed in UTF-8 or any other Unicode Transformation Format (such as `"\uDEAD"`): https://www.rfc-editor.org/rfc/rfc8259#section-8.2

But there is an "I-JSON" RFC defining a subset prohibiting such strings and duplicate object member names, and also effectively limiting numbers to IEEE 754 binary64 values on the receiver side without imposing a hard restriction on actual serializations: https://www.rfc-editor.org/rfc/rfc7493

Speaking on the other point, I think we should maintain implementation consistency: either require everyone to accept and preserve representations of strings containing arbitrary sequences of UTF-16 code units as in JSON, or else require everyone to reject as invalid any message in which an included string cannot be represented in (w.l.o.g.) UTF-8.

**Comment by dpwiz** [comment]
> The behavior of software that receives JSON texts containing such values is unpredictable; for example, implementations might return different values for the length of a string value or even suffer fatal runtime exceptions.

That sounds bad.

However, the section leads with:

> *When* all the strings represented in a JSON text are composed entirely of Unicode characters (however escaped), then that JSON text is interoperable...

So, do we want being "interoperable" or not? If yes, then this spec cannot mandate arbitrary binary data in texts. Implementations of course can do whatever they want (when not relying on *inter*-operability with other systems.

**Comment by dckc** [comment]
In notes from the recent meeting (#99) I see:
> ACCEPTED: OCapN will specify that strings MUST be valid UTF-8 on both outgoing messages and on incoming (requiring a validation step).

That suggests closing this issue, but ... did anyone take the ball to add tests?


> Any understanding that (you think) is established without a basis in black-and-white test cases and/or
code will almost certainly vaporize as soon as a few new people join the activity, or as soon as the results of the activity are presented to a wider audience.
 -- [Jos D quoting yours truly, 2010](https://www.w3.org/blog/2010/thanks-for-a-great-15-years-at/#comment-81483)

**Comment by erights** [comment]
> That suggests closing this issue, but ... did anyone take the ball to add tests?

I did not. Looking now at https://github.com/tc39/proposal-is-usv-string .

**Comment by erights** [comment]
which is stage 4, and therefore almost certainly an official part of JS.

**Comment by erights** [comment]
Already on the ses-shim permits.js list since https://github.com/endojs/endo/pull/1618 . Already implemented and available on Node 20.

But not on Node 16 or 18. What about XS?

**Comment by erights** [comment]
@gibson042 , if we shim `isWellFormed` ourselves for XS, we'll need to avoid `[i]` and use a string iterator.

**Comment by gibson042** [comment]
> @gibson042 , if we shim `isWellFormed` ourselves for XS, we'll need to avoid `[i]` and use a string iterator.

Sure, it's pretty much trivial:
```js
const isWellFormed = str => {
  for (const ch of str) {
    const cp = ch.codePointAt(0);
    if (0xD800 <= cp && cp <= 0xDFFF) return false;
  }
  return true;
};
```

**Comment by erights** [comment]
> That suggests closing this issue, but ... did anyone take the ball to add tests?

@dckc, 
How about https://github.com/endojs/endo/pull/2002 ?

**Comment by dckc** [comment]
Well, I suppose that's relevant, but I was asking about [ocapn tests](https://github.com/ocapn/ocapn-test-suite).

**Comment by erights** [comment]
Reopening, because https://github.com/endojs/endo/pull/2002 itself hides the feature behind a feature flag that we currently have disabled by default. Once we change this to default to enabled, then we can close this issue.
