### ISSUE TITLE
Agenda for group

### ISSUE THREAD

**Issue by kriskowal** [ocapn/ocapn#9]
I propose an agenda for this group based on the conversation we had this morning.

1. We should first establish our explicit goals and non-goals. For example, we have loose consensus that our goal is to bridge Agoric, Goblins, CloudFlare Works, and Sandstorm applications after some fashion. We have loose consensus that brevity on the wire is a non-goal. We have loose consensus that at least Agoric and Goblins will be able to communicate without an IDL. We should establish whether messages are at most graphs, dags, or trees. We have loose consensus that this CapTP will allow API’s to be framed either in terms of function application or method invocation and that it is generally a non-goal to hide the idioms of an API’s first implementation language. Throughout this phase of conversation, we may propose straw-men for codec but we agree that we’re not committed to any particulars.

2. We should then establish what kinds of messages and data #5 can transit this CapTP and how they will be represented in each participating language. For example, we have established that JavaScript objects correspond to structs in most languages. We currently believe that a JavaScript number corresponds to a Racket double precision floating point number and that a JavaScript bigint corresponds to a Racket integer. In this phase, we establish more values for the serialization format, like suitability for binary data.

3. Once we’ve established all of the above goal-posts, we should select a serialization format. The options are to create a meta-protocol on an existing serialization format, customize one, or create one.

The objective is, within a bounded time, to arrive at a concrete implementation of a CapTP suitable for conversation amongst the involved projects. The intention of this format is to avoid a bike-shed until we have consensus on goal-posts.

**Comment by kriskowal** [comment]
I will petition @erights or @dtribble to speak to a concrete time budget for advancing this conversation, but emphatically, we are not in a hurry and our pace will likely be motivated by extrinsic considerations like pressure to support binary data or other features with our own CapTP, when they may as well be aligned with this group’s agenda. My hope is that this conversation will put us in a better position to have answers to design questions ready just before we need to commit to a binary CapTP design.

**Comment by zenhack** [comment]
> We should establish whether messages are at most graphs, dags, or trees.

The sense I got from the call is that of the involved systems, only Cloudflare Workers has interest in anything more general than trees. In addition, Cloudflare Workers is built on top of capnp, so already the graphs it includes have to fit into capnp's tree-expecting format. If I understood correctly (@kentonv correct me if I'm wrong), right now it just uses v8's serialization for structured clone and then embeds the whole thing as a blob inside a larger capnproto message, so realistically that would probably have to change if the graphs were to be sent to systems outside of cloudflare workers. The way I've seen graphs represented in capnp is to convert them into a list and have them refer to one another by id/index, as in [schema.capnp][1]. My inclination is to not impose supporting graphs on implementations, and instead expect applications that need graphs to do something similar to that.

[1]: https://github.com/capnproto/capnproto/blob/78b1da896731806d34470e24ad67098f9507d8f6/c%2B%2B/src/capnp/schema.capnp#L507

**Comment by kentonv** [comment]
@zenhack That's correct.

Phrased differently: Cap'n Proto has no interest in supporting graphs, only trees. Cloudflare Workers is likely to use V8 serialization embedded inside Cap'n Proto RPC. V8 serialization implements the semantics of Structured Clone, which supports arbitrary graphs. The reason Workers wants to use V8 serialization is because Workers is a JavaScript platform, and structured clone is well-defined and understood in the JS ecosystem today. It leads to the best experience for JS developers.

This approach only makes sense when calling between JS environments. As soon as any other language is involved, Structured Clone becomes warty and thus loses its value. We only intend to use this for Worker-to-Worker communications. For any communication with the rest of the world, we'd do something different. For instance, if we wanted to enable communicating with third-party Cap'n Proto servers, then we'd require the application to provide a capnp schema, and we'd define some way to manipulate particular schemas in JavaScript.

FWIW, I tend to believe that there's no such thing as a language-neutral dynamically-typed serialization.

**Comment by erights** [comment]
I also endorse only trees. In E I supported pass-by-copy graphs whose equality was based on their equivalence under infinite unwinding, also known as "infinite rational trees". At Agoric, we started with support for serializing and deserializing cycles, but never did the work to compare them correctly. Then we retired support for trees but kept support for DAGs. Then we retired support for DAGs and now support only trees. Before going from DAGs to trees, I instrumented to see when we'd have a net space cost. Essentially never on actual cases, even though these actual cases could have been constructed at that time under assumption of a space savings.

**Comment by zenhack** [comment]
Ok, looks like we're agreed on trees then. Turning @kriskowal's goals paragraph into a list for organization:

- we have loose consensus that our goal is to bridge Agoric, Goblins, CloudFlare Works, and Sandstorm applications after some fashion.
- We have loose consensus that brevity on the wire is a non-goal.
- We have loose consensus that at least Agoric and Goblins will be able to communicate without an IDL.
- ~We should establish whether messages are at most graphs, dags, or trees.~ We have a consensus that messages are trees; graphs (cyclic or otherwise) cannot be directly represented.
- We have loose consensus that this CapTP will allow API’s to be framed either in terms of function application or method invocation and that it is generally a non-goal to hide the idioms of an API’s first implementation language.

Is there anything else we should add to this list?

**Comment by kriskowal** [comment]
We have tentative agreement:

- We seek to interoperate initially between Agoric and Spritely implementations of OCapN in JavaScript and Guile.
- The abstract passable data model. #5 
- Beginning with a Syrup based concrete syntax.
