### ISSUE TITLE
November 2023 meeting

### ISSUE THREAD

**Issue by jar398** [ocapn/ocapn#94]
**Date/time**: 2nd Tuesday [19:00 UTC on 14 November 2023](https://www.timeanddate.com/worldclock/converter.html?iso=20231114T190000&p1=239&p2=1440&p3=43&p4=1240).
**Location**: https://bbb.sfconservancy.org/b/chr-pm5-cl8-ctl
**Scribe**: volunteer sought
**Preliminary agenda**:
 * Closed issues - discussion only if there are objections
 * Old business
      * OK to merge? https://github.com/ocapn/ocapn/pull/84 @tsyesika 
      * Keep multiple value fulfillment? https://github.com/ocapn/ocapn/issues/55#issuecomment-1721720435 @tsyesika 
 * OK to merge? https://github.com/ocapn/ocapn/pull/97
 * OK to merge? https://github.com/ocapn/ocapn/pull/96 
 * Subcommittee report on abstract syntax (document:  https://github.com/ocapn/ocapn/wiki/Abstract-Syntax) @kriskowal 
     * Do we have consensus on what this document says?  If not  what changes are needed?
 * What to do about strings with regard to lone surrogate and UTF-16?  Analysis by @cwebber:  https://github.com/ocapn/ocapn/issues/47#issuecomment-1773358107  with links to relevant external documents.

**Comment by tsyesika** [comment]
There's a few more things we could add to the agenda:
- https://github.com/ocapn/ocapn/pull/97
- The abstract syntax document https://github.com/ocapn/ocapn/wiki/Abstract-Syntax
- Related to above, discussing the issue of strings with regard to lone surrogate and UTF-16. I think furthering the discussion here would be useful. Important to note @cwebber  added this comment since last meeting:  https://github.com/ocapn/ocapn/issues/47#issuecomment-1773358107.
- https://github.com/ocapn/ocapn/pull/96 

I suspect that's too much to get through in one meeting so I tried to put them in some rough order.

**Comment by jar398** [comment]
@tsyesika Added to agenda. Thanks.

**Comment by kriskowal** [comment]
Changes to the Abstract Syntax from consensus building during this meeting:
https://github.com/ocapn/ocapn/wiki/Abstract-Syntax/_compare/793f7124a486aff4f4c0aa10c1d890d21080d228...8956c761067d8f52012f8c6d7ef515e78b019de2

**Comment by tsyesika** [comment]
A PR with the meeting minutes is ready for review here: https://github.com/ocapn/ocapn/pull/98

**Comment by jar398** [comment]
The meeting took place and a link to the minutes is posted above.
