### ISSUE TITLE
Jan 2024 meeting

### ISSUE THREAD

**Issue by jar398** [ocapn/ocapn#99]
**Date/time**: 2nd Tuesday [19:00 UTC on 9 January 2024](https://www.timeanddate.com/worldclock/converter.html?iso=20240109T190000&p1=239&p2=1440&p3=43&p4=1240).
**Location**: https://bbb.sfconservancy.org/b/chr-pm5-cl8-ctl
**Scribe**: volunteer sought
**Preliminary agenda**:
 * Closed issues - discussion only if there are objections (none?)
 * Review results of poll on type name bytevector, bytestring, bytearray [link to poll](https://github.com/ocapn/ocapn/issues/48#issuecomment-1811097196)
 * Strings.  @tsyesika: "I think https://github.com/ocapn/ocapn/issues/47#issuecomment-1808648754 specifically covers the current state of things" 
 * Review process for merging PRs - keep as is (each PR gets group review at a meeting) or try to streamline the way issue closing is done?
  * Review [open pull requests](https://github.com/ocapn/ocapn/pulls)
  
  [Minutes of November meeting](https://github.com/ocapn/ocapn/pull/98) to be merged as soon as this meeting is over.

**Comment by tsyesika** [comment]
The poll for the name for bytevector/bytestring/bytearray: https://github.com/ocapn/ocapn/issues/48#issuecomment-1811097196

**Comment by jar398** [comment]
It's a pretty thin agenda.  Absent technically substantive topics, or advocacy for the urgency of what I've proposed so far, we might consider postponing until January.

Topic suggestions?

**Comment by cwebber** [comment]
I vote we postpone.  Common for december standards meetings.

**Comment by jar398** [comment]
Hearing no further discussion, I declare the December meeting postponed and renamed to be the January meeting.

**Comment by tsyesika** [comment]
Since the agenda's currently looking a bit thin, can I propose that we continue our discussion on Strings, specifically #47.

I think [this comment](https://github.com/ocapn/ocapn/issues/47#issuecomment-1808648754) specifically covers the current state of things, this is:

I believe we have broad agreement to support UTF-8 only,  there is/was an open question around what to do with invalid strings (I think proposed was to simply validate and reject all invalid strings rather than trying to round trip them). Also for Agoric, my understanding is supporting any JSON string representation is important and there seems to be some uncertainty around what JSON requires.

I think it'd be good if we could reach consensus on this and document that in our [abstract syntax doc](https://github.com/ocapn/ocapn/wiki/Abstract-Syntax#strings-json)

**Comment by jar398** [comment]
Thanks @tsyesika .

A general reminder that our meeting is in six days (Jan 9).  Agenda suggestions welcome.

**Comment by zarutian** [comment]
[Cryptpad meeting minutes](https://cryptpad.fr/code/#/2/code/edit/Ng7kXl9rCF5qnTQX60UCpDHE/)

**Comment by jar398** [comment]
Minutes PR for this meeting: https://github.com/ocapn/ocapn/pull/102
